wandb_version: 1

seed:
  desc: null
  value: 4
dataset:
  desc: null
  value: mnist
n_init:
  desc: null
  value: 20
n_max:
  desc: null
  value: 100
optimizer:
  desc: null
  value: adam
lr:
  desc: null
  value: 0.001
lr_min:
  desc: null
  value: 1.0e-05
n_epochs:
  desc: null
  value: 2000
batch_size:
  desc: null
  value: 256
method:
  desc: null
  value: epig_model
approx:
  desc: null
  value: kron
lr_hyp:
  desc: null
  value: 0.1
lr_hyp_min:
  desc: null
  value: 0.01
n_epochs_burnin:
  desc: null
  value: 10
marglik_frequency:
  desc: null
  value: 10
n_hypersteps:
  desc: null
  value: 50
early_stopping:
  desc: null
  value: true
validation:
  desc: null
  value: false
last_layer:
  desc: null
  value: false
n_components:
  desc: null
  value: 10
device:
  desc: null
  value: cpu
data_root:
  desc: null
  value: data/
download_data:
  desc: null
  value: true
use_wandb:
  desc: null
  value: true
random_acquisition:
  desc: null
  value: true
methodconf:
  desc: null
  value: mnist_epig
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703078281.177595
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
