dataset: mnist
lr: 1e-3
lr_min: 1e-5
lr_hyp: 0.01
lr_hyp_min: 0.001
n_max: 100
optimizer: adam
n_epochs: 3000
batch_size: 256
device: cuda
download_data: True
n_epochs_burnin: 750
marglik_frequency: 50
data_root: data/
acquisition_method: epig
last_layer: True