dataset: mnist
lr: 1e-3
lr_min: 1e-5
n_max: 100
optimizer: adam
n_epochs: 2000
batch_size: 256
device: cuda
download_data: True
n_epochs_burnin: 500
marglik_frequency: 50
data_root: data/
acquisition_method: bald